# Missing Data (Week 2 tutorial, notebook 4 of 8)

**What this notebook covers:** three ways to deal with missing values (`NaN`) in pandas: drop the rows or columns that contain them (`dropna`), keep only the rows with enough values (`thresh`), or fill the gaps (`fillna`), for example with a constant or with the column mean. These are the *ignore the tuple*, *global constant* and *attribute mean* methods from the lecture slide "How to Handle Missing Data?".

**How to run it:** this notebook runs in your browser, so there is nothing to install. Click a code cell and press **Shift + Enter** to run it and move to the next one, or use **Run → Run All Cells**. Run the cells in order, because later cells use variables created earlier.

**What to expect:** a small table with three missing values, followed by the result of each method.

**Next:** *05-Groupby*.

## Methods

Let's show a few convenient methods to deal with Missing Data in pandas. The example table has missing values (`np.nan`) in columns A and B; column C is complete.

In [1]:
import numpy as np
import pandas as pd

In [9]:
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})

In [10]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

`dropna` removes data and `fillna` replaces it. Neither changes `df` itself: each returns a new table.

In [12]:
# drop every row that has at least one missing value
df.dropna()

     A    B  C
0  1.0  5.0  1

In [13]:
# drop every column that has a missing value
df.dropna(axis=1)

   C
0  1
1  2
2  3

In [14]:
# keep only the rows with at least 2 values that are not missing
df.dropna(thresh=2)

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

Filling with text turns columns A and B into general Python objects, so their numbers are shown as `1.0` and `5.0` next to the text. In practice you fill a number column with a number, as in the next cell.

In [15]:
# replace every missing value with the same constant
df.fillna(value='FILL VALUE')

            A           B  C
0         1.0         5.0  1
1         2.0  FILL VALUE  2
2  FILL VALUE  FILL VALUE  3

In [17]:
# fill the gap in column A with the mean of its known values: (1 + 2) / 2 = 1.5
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

**Try it:** what does `df.dropna(thresh=3)` return?

<details><summary>Answer</summary>

Only row 0, the one row with all three values present.

</details>

# Great Job!