# Groupby (Week 2 tutorial, notebook 5 of 8)

**What this notebook covers:** `groupby`, which splits a table into groups by the values in one column, applies a summary such as the mean, standard deviation, minimum, maximum or count to each group, and combines the results. This is the *aggregation* step from the lecture.

**How to run it:** this notebook runs in your browser, so there is nothing to install. Click a code cell and press **Shift + Enter** to run it and move to the next one, or use **Run → Run All Cells**. Run the cells in order, because later cells use variables created earlier.

**What to expect:** a small table of sales by company and person, then one summary row per company.

**Next:** *06-Merging, Joining, and Concatenating*.

## Grouping rows

The groupby method allows you to group rows of data together and call aggregate functions.

In [31]:
import pandas as pd
# Create dataframe: one row per salesperson
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [32]:
df = pd.DataFrame(data)

In [33]:
df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

**Now you can use the .groupby() method to group rows together based off of a column name. For instance let's group based off of Company. This will create a DataFrameGroupBy object:**

On its own, the object only shows its type and memory address. It holds the groups until you ask for a summary.

In [34]:
df.groupby('Company')

You can save this object as a new variable:

In [35]:
by_comp = df.groupby("Company")

And then call aggregate methods off the object. `numeric_only=True` tells pandas to summarise only the number columns: the mean of the names in `Person` cannot be computed, and current pandas versions stop with a `TypeError` without this option.

In [36]:
by_comp.mean(numeric_only=True)

         Sales
Company
FB       296.5
GOOG     160.0
MSFT     232.0

In [37]:
df.groupby('Company').mean(numeric_only=True)

         Sales
Company
FB       296.5
GOOG     160.0
MSFT     232.0

More examples of aggregate methods. `min` and `max` also work on text (in alphabetical order), and `count` counts the values that are not missing in each column.

In [38]:
by_comp.std(numeric_only=True)

              Sales
Company
FB        75.660426
GOOG      56.568542
MSFT     152.735065

In [39]:
by_comp.min()

          Person  Sales
Company
FB          Carl    243
GOOG     Charlie    120
MSFT         Amy    124

In [40]:
by_comp.max()

          Person  Sales
Company
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [41]:
by_comp.count()

         Person  Sales
Company
FB            2      2
GOOG          2      2
MSFT          2      2

`describe()` gives the count, mean, standard deviation, minimum, quartiles and maximum of each group at once. `transpose()` swaps rows and columns, and `['GOOG']` then picks one company.

In [42]:
by_comp.describe()

        Sales
        count   mean         std    min     25%    50%     75%    max
Company
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [43]:
by_comp.describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

In [44]:
by_comp.describe().transpose()['GOOG']

Sales  count      2.000000
       mean     160.000000
       std       56.568542
       min      120.000000
       25%      140.000000
       50%      160.000000
       75%      180.000000
       max      200.000000
Name: GOOG, dtype: float64

**Try it:** which company has the highest total sales? Use `by_comp.sum(numeric_only=True)`.

<details><summary>Answer</summary>

FB, with 243 + 350 = 593 (GOOG 320, MSFT 464). Without `numeric_only=True`, `sum` also joins the names in `Person` into one string, such as `CarlSarah`.

</details>

# Great Job!