# Operations (Week 2 tutorial, notebook 7 of 8)

**What this notebook covers:** everyday operations on a DataFrame: unique values and counts, selecting with several conditions, applying a function to every value, deleting columns, sorting, checking for and filling missing values, and summarising a table with `pivot_table`.

**How to run it:** this notebook runs in your browser, so there is nothing to install. Click a code cell and press **Shift + Enter** to run it and move to the next one, or use **Run → Run All Cells**. Run the cells in order, because later cells use variables created earlier.

**What to expect:** a small table that changes as you go: `col1` is deleted part-way through, and later cells build new tables.

**Next:** *08-Data Input and Output*.

## Useful operations

There are lots of operations with pandas that will be really useful to you, but don't fall into any distinct category. Let's show them here in this lecture:

In [52]:
import pandas as pd
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

### Info on Unique Values

`unique` lists the distinct values, `nunique` counts them, and `value_counts` counts how often each value occurs, most frequent first. On the course website `unique()` may also show `dtype=int64` after the list, because the browser version of Python uses 32-bit whole numbers by default; the values are the same.

In [53]:
df['col2'].unique()

array([444, 555, 666])

In [54]:
df['col2'].nunique()

3

In [55]:
df['col2'].value_counts()

col2
444    2
555    1
666    1
Name: count, dtype: int64

### Selecting Data

In [56]:
#Select from DataFrame using criteria from multiple columns
newdf = df[(df['col1']>2) & (df['col2']==444)]

In [57]:
newdf

   col1  col2 col3
3     4   444  xyz

### Applying Functions

`apply` calls a function on every value of a column and returns the results as a new Series. Any function that takes one value works, your own (`times2`) or a built-in one such as `len`.

In [58]:
def times2(x):
    return x*2

In [59]:
# apply times2 to every value of col1
df['col1'].apply(times2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [60]:
df['col3'].apply(len)

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [61]:
df['col1'].sum()

np.int64(10)

**Permanently removing a column**

`del` changes `df` itself, unlike `drop` without `inplace=True`.

In [62]:
del df['col1']

In [63]:
df

   col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

**Get column and index names:**

In [64]:
df.columns

Index(['col2', 'col3'], dtype='str')

In [65]:
df.index

RangeIndex(start=0, stop=4, step=1)

**Sorting and ordering a DataFrame:**

In [66]:
df

   col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [67]:
df.sort_values(by='col2') #inplace=False by default

   col2 col3
0   444  abc
3   444  xyz
1   555  def
2   666  ghi

**Find null values or check for null values**

`isnull()` marks each missing value with True. This table has none, so `dropna()` returns it unchanged.

In [68]:
df.isnull()

    col2   col3
0  False  False
1  False  False
2  False  False
3  False  False

In [69]:
# Drop rows with NaN Values
df.dropna()

   col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

**Filling in NaN values with something else:**

Filling with text turns the number columns into general Python objects, so their numbers are shown as `1.0`, `555.0` and so on.

In [71]:
import numpy as np

In [72]:
df = pd.DataFrame({'col1':[1,2,3,np.nan],
                   'col2':[np.nan,555,666,444],
                   'col3':['abc','def','ghi','xyz']})
df.head()

   col1   col2 col3
0   1.0    NaN  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   NaN  444.0  xyz

In [75]:
df.fillna('FILL')

   col1   col2 col3
0   1.0   FILL  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3  FILL  444.0  xyz

**Pivot tables:** `pivot_table` summarises column `D` with one row for each combination of `A` and `B` and one column for each value of `C`. Each cell is the mean of the matching `D` values (here each combination occurs at most once); `NaN` means the combination does not occur.

In [89]:
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)

In [90]:
df

     A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [91]:
df.pivot_table(values='D',index=['A', 'B'],columns=['C'])

C          x    y
A   B
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

**Try it:** add `aggfunc='sum', fill_value=0` to the `pivot_table` call. What changes?

<details><summary>Answer</summary>

The empty cells show `0` instead of `NaN`, and the values are whole numbers (`4` instead of `4.0`), because no `NaN` is left to force decimals.

</details>

# Great Job!