# Data Input and Output (Week 2 tutorial, notebook 8 of 8)

**What this notebook covers:** reading and writing CSV and Excel files, reading a table from an HTML page, and writing to and reading from an SQL database.

**How to run it:** this notebook runs in your browser, so there is nothing to install. Click a code cell and press **Shift + Enter** to run it and move to the next one, or use **Run → Run All Cells**. Run the cells in order, because later cells use variables created earlier. The first code cell installs `lxml` (for HTML) and `openpyxl` (for Excel) into the browser, which takes a few seconds the first time.

**What to expect:** the files `example.csv`, `Excel_Sample.xlsx` and `banklist.html` are in the same folder as this notebook, so pandas finds them by name. The cells that write files change your own copy in the browser only; the files on the course website are not affected.

**Next:** this is the last notebook of the set.

## Overview

This notebook is the reference code for getting input and output. pandas can read a variety of file types using its `pd.read_` methods. Let's take a look at the most common data types:

In [1]:
%pip install lxml openpyxl
# lxml reads HTML tables and openpyxl reads and writes Excel files
import numpy as np
import pandas as pd

## CSV

### CSV Input

`example.csv` is a small comma-separated text file.

In [25]:
df = pd.read_csv('example.csv')
df

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

### CSV Output

`index=False` leaves out the row labels 0 to 3, so the file keeps its four original columns.

In [24]:
df.to_csv('example.csv',index=False)

## Excel
Pandas can read and write excel files, keep in mind, this only imports data. Not formulas or images, having images or macros may cause this read_excel method to crash.

### Excel Input

`sheet_name` picks the worksheet (older pandas versions called it `sheetname`). The first column, `Unnamed: 0`, is a row index that was saved into the file without a header; add `index_col=0` to use it as the index instead.

In [35]:
pd.read_excel('Excel_Sample.xlsx',sheet_name='Sheet1')

   Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

### Excel Output

`to_excel` also saves the row index as the first column, which is where the `Unnamed: 0` column above comes from.

In [33]:
df.to_excel('Excel_Sample.xlsx',sheet_name='Sheet1')

## HTML

pandas can read tables from HTML pages. It needs the `lxml` library, which the first code cell installed. On your own computer, install it once with `pip install lxml` (or `conda install lxml` if you use Anaconda).

This example originally read the FDIC Failed Bank List straight from the web (it is now at https://www.fdic.gov/bank-failures/failed-bank-list, split over several pages). Python running in the browser cannot download a page from another website this way, so this notebook reads a saved copy, `banklist.html`, with 60 of the 545 banks the list had in 2016 (the 30 most recent and the 30 oldest).

### HTML Input

Pandas read_html function will read tables off of a webpage and return a list of DataFrame objects, one for each table on the page, so `tables[0]` is the first table:

In [5]:
# on your own computer you can pass a web address instead of a file name
tables = pd.read_html('banklist.html')

In [7]:
tables[0]

                                     Bank Name  ... Termination Date
0                       First CornerStone Bank  ...              NaN
1                           Trust Company Bank  ...              NaN
2                   North Milwaukee State Bank  ...              NaN
3                       Hometown National Bank  ...              NaN
4                          The Bank of Georgia  ...              NaN
5                                 Premier Bank  ...              NaN
6                               Edgebrook Bank  ...              NaN
7                         Doral BankEn Espanol  ...              NaN
8            Capitol City Bank & Trust Company  ...              NaN
9                      Highland Community Bank  ...              NaN
10            First National Bank of Crestview  ...              NaN
11                          Northern Star Bank  ...              NaN
12      Frontier Bank, FSB D/B/A El Paseo Bank  ...              NaN
13       The National Republic Bank of Chicago  ...              NaN
14                              NBRS Financial  ...              NaN
15                       GreenChoice Bank, fsb  ...              NaN
16                    Eastside Commercial Bank  ...              NaN
17                      The Freedom State Bank  ...              NaN
18                                 Valley Bank  ...              NaN
19                                 Valley Bank  ...              NaN
20                 Slavie Federal Savings Bank  ...              NaN
21                       Columbia Savings Bank  ...              NaN
22                AztecAmerica Bank En Espanol  ...              NaN
23                       Allendale County Bank  ...              NaN
24                          Vantage Point Bank  ...              NaN
25       Millennium Bank, National Association  ...              NaN
26                                Syringa Bank  ...              NaN
27                           The Bank of Union  ...              NaN
28                        DuPage National Bank  ...              NaN
29  Texas Community Bank, National Association  ...              NaN
30                           ANB Financial, NA  ...              NaN
31                                   Hume Bank  ...              NaN
32                      Douglass National Bank  ...              NaN
33                           Miami Valley Bank  ...              NaN
34                                     NetBank  ...              NaN
35                   Metropolitan Savings Bank  ...              NaN
36                             Bank of Ephraim  ...              NaN
37                               Reliance Bank  ...              NaN
38       Guaranty National Bank of Tallahassee  ...              NaN
39                         Dollar Savings Bank  ...              NaN
40                        Pulaski Savings Bank  ...              NaN
41       First National Bank of Blanchardville  ...              NaN
42                       Southern Pacific Bank  ...              NaN
43                 Farmers Bank of Cheneyville  ...              NaN
44                               Bank of Alamo  ...              NaN
45        AmTrade International BankEn Espanol  ...              NaN
46              Universal Federal Savings Bank  ...              NaN
47                Connecticut Bank of Commerce  ...              NaN
48                            New Century Bank  ...              NaN
49                       Net 1st National Bank  ...              NaN
50                                NextBank, NA  ...              NaN
51                    Oakwood Deposit Bank Co.  ...              NaN
52                       Bank of Sierra Blanca  ...              NaN
53                 Hamilton Bank, NAEn Espanol  ...              NaN
54                      Sinclair National Bank  ...              NaN
55                          Superior Bank, FSB  ...              NaN
56                         Malta National Bank  ...              NaN
57             First Alliance Bank & Trust Co.  ...              NaN
58           National State Bank of Metropolis  ...              NaN
59                            Bank of Honolulu  ...              NaN

[60 rows x 10 columns]

____

_____
_____
# SQL (Optional)

This section uses SQLite, a small database that runs inside Python, so there is no database server to set up.

The pandas.io.sql module provides a collection of query wrappers to both facilitate data retrieval and to reduce dependency on DB-specific API. Database abstraction is provided by SQLAlchemy if installed. In addition you will need a driver library for your database. Examples of such drivers are psycopg2 for PostgreSQL or pymysql for MySQL. For SQLite this is included in Python’s standard library.

If SQLAlchemy is not installed, pandas can still work with SQLite through a plain `sqlite3` connection. For more examples, see the section "SQL queries" in the pandas user guide: https://pandas.pydata.org/docs/user_guide/io.html

The key functions are:

* read_sql_table(table_name, con[, schema, ...])
    * Read SQL database table into a DataFrame.
* read_sql_query(sql, con[, index_col, ...])
    * Read SQL query into a DataFrame.
* read_sql(sql, con[, index_col, ...])
    * Read SQL query or database table into a DataFrame.
* DataFrame.to_sql(name, con[, schema, ...])
    * Write records stored in a DataFrame to a SQL database.

In [36]:
from sqlalchemy import create_engine

`create_engine('sqlite:///:memory:')` creates a temporary database in memory. `to_sql` writes `df` into a table called `data` and returns the number of rows written (4); `read_sql` reads the table back. The extra `index` column is the DataFrame's index, which `to_sql` saves by default.

In [37]:
engine = create_engine('sqlite:///:memory:')

In [40]:
# write df into a new table called 'data'
df.to_sql('data', engine)

4

In [42]:
sql_df = pd.read_sql('data',con=engine)

In [43]:
sql_df

   index   a   b   c   d
0      0   0   1   2   3
1      1   4   5   6   7
2      2   8   9  10  11
3      3  12  13  14  15

**Try it:** run `pd.read_sql('SELECT a, d FROM data WHERE a > 4', con=engine)`. What do you get?

<details><summary>Answer</summary>

Two rows: `a` = 8, `d` = 11 and `a` = 12, `d` = 15. `read_sql` also accepts an SQL query instead of a table name.

</details>

# Great Job!